spring:
  application:
    name: lockr
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: jdbc:mysql://${LOCKR_DATA_SOURCE_URL:localhost:3306/lockr}
    username: ${LOCKR_DATA_SOURCE_USER_NAME:root}
    password: ${LOCKR_DATA_SOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: mysql
logging:
  level:
    root: INFO
