### 스쿼드 조회
GET http://127.0.0.1:8080/api/v1/clubs/{{CLUB_ID}}/squads
Cookie: {{SESSION_COOKIE_2}}
Content-Type: application/json
Authorization: test
X-DEVICE-ID: 1
X-DEVICE-INFO: web

> {%
    client.global.set("SQUAD_ID", response.body.id);
    client.global.set("CLUB_ID", response.body.clubId);
    client.global.set("SQUAD_PLAYER_ID_3", response.body.squadPlayers[2].id);
%}

#### 전술 보드 생성
POST http://127.0.0.1:8080/api/v1/clubs/{{CLUB_ID}}/boards
Cookie: {{SESSION_COOKIE_2}}
Content-Type: application/json
Authorization: test
X-DEVICE-ID: 1
X-DEVICE-INFO: web

{
  "name": "4-3-3 Formation"
}
> {%
    client.global.set("TACTICAL_BOARD_ID", response.body.id);
%}

###
POST http://127.0.0.1:8080/api/v1/clubs/{{CLUB_ID}}/boards/{{TACTICAL_BOARD_ID}}/player
Cookie: {{SESSION_COOKIE_2}}
Content-Type: application/json
Authorization: test
X-DEVICE-ID: 1
X-DEVICE-INFO: web

{
  "playerId": "{{SQUAD_PLAYER_ID_3}}",
  "playerType": "FIELD",
  "x": 40,
  "y": 80
}

###
POST http://127.0.0.1:8080/api/v1/clubs/{{CLUB_ID}}/boards/{{TACTICAL_BOARD_ID}}/formation
Cookie: {{SESSION_COOKIE_2}}
Content-Type: application/json
Authorization: test
X-DEVICE-ID: 1
X-DEVICE-INFO: web

{
  "formationName": "352"
}

###
GET http://127.0.0.1:8080/api/v1/clubs/{{CLUB_ID}}/squads
Cookie: {{SESSION_COOKIE_2}}
Content-Type: application/json
Authorization: test
X-DEVICE-ID: 1
X-DEVICE-INFO: web

> {%
    client.global.set("SQUAD_ID", response.body.id);
    client.global.set("CLUB_ID", response.body.clubId);
    client.global.set("SQUAD_PLAYER_ID_3", response.body.squadPlayers[2].id);
%}

###
POST http://127.0.0.1:8080/api/v1/clubs/{{CLUB_ID}}/boards/{{TACTICAL_BOARD_ID}}/move/location
Cookie: {{SESSION_COOKIE_2}}
Content-Type: application/json
Authorization: test
X-DEVICE-ID: 1
X-DEVICE-INFO: web

{
  "playerId": "{{SQUAD_PLAYER_ID_3}}",
  "x": 20,
  "y": 80
}
