#### 로그인
POST http://127.0.0.1:8080/api/v1/admin/auth/sign_in
Content-Type: application/json
Authorization: test
X-DEVICE-ID: 1
X-DEVICE-INFO: web

{
  "providerId": "1",
  "providerType": "TEST"
}
> {%
    client.global.set("SESSION_COOKIE", response.headers.valueOf("Set-Cookie"));
%}
