-- Task 4.1: ScheduleType 네이밍 정합성 (HAPPY_HOUR -> SOCIAL_EVENT)
ALTER TABLE schedules MODIFY COLUMN type VARCHAR(50) NOT NULL COMMENT '일정 타입 (MATCH, TRAINING, SOCIAL_EVENT)';

-- Task 4.2: AttendanceStatus TENTATIVE 제거
ALTER TABLE attendances MODIFY COLUMN status VARCHAR(50) NOT NULL COMMENT '참석 상태 (ATTENDING, NOT_ATTENDING, NO_RESPONSE)';
